[extern]
pid = "xxx.txt"
close_emoji = "xxx"

[bots]

    [bots.rp]
        bot = true
        token = "XXXXXXXXXXXXXXXXXXXXXXXXX"
        guild = "XXXXXXXXXXXXXXXXXXXXXX"
        sup_cat = "XXXXXXXXXXXXXXXXXXXXXX"
        ready_chan = "XXXXXXXXXXXXXXXXXXXXXX"
